INSERT INTO products (prod_id, prod_name, prod_desc, price, unit) VALUES ('4', 'Apple', 'apple cell phone', 500, '10');
INSERT INTO products (prod_id, prod_name, prod_desc, price, unit) VALUES ('2', 'Dell', 'dell computer', 3000, '5');
INSERT INTO products (prod_id, prod_name, prod_desc, price, unit) VALUES ('3', 'office', 'ms office software', 196, '23');
INSERT INTO products (prod_id, prod_name, prod_desc, price, unit) VALUES ('1', 'Apple', 'apple cell phone', 500, '10');
INSERT INTO products (prod_id, prod_name, prod_desc, price, unit) VALUES ('7', 'Apple', 'apple cell phone', 500, '10');
INSERT INTO products (prod_id, prod_name, prod_desc, price, unit) VALUES ('6', 'office', 'ms office software', 196, '23');
INSERT INTO products (prod_id, prod_name, prod_desc, price, unit) VALUES ('5', 'Dell', 'dell computer', 3000, '5');
INSERT INTO products (prod_id, prod_name, prod_desc, price, unit) VALUES ('8', 'Dell', 'dell computer', 3000, '5');
INSERT INTO products (prod_id, prod_name, prod_desc, price, unit) VALUES ('10', 'Apple', 'apple cell phone', 500, '10');
INSERT INTO products (prod_id, prod_name, prod_desc, price, unit) VALUES ('11', 'Dell', 'dell computer', 3000, '5');
INSERT INTO products (prod_id, prod_name, prod_desc, price, unit) VALUES ('12', 'office', 'ms office software', 196, '23');
INSERT INTO products (prod_id, prod_name, prod_desc, price, unit) VALUES ('9', 'office', 'ms office software', 196, '23');
INSERT INTO products (prod_id, prod_name, prod_desc, price, unit) VALUES ('16', 'office', 'ms office software', 196, '23');
INSERT INTO products (prod_id, prod_name, prod_desc, price, unit) VALUES ('15', 'Dell', 'dell computer', 3000, '5');
INSERT INTO products (prod_id, prod_name, prod_desc, price, unit) VALUES ('14', 'Apple', 'apple cell phone', 500, '10');
INSERT INTO products (prod_id, prod_name, prod_desc, price, unit) VALUES ('13', 'office', 'ms office software', 196, '23');
INSERT INTO products (prod_id, prod_name, prod_desc, price, unit) VALUES ('18', 'Dell', 'dell computer', 3000, '5');
INSERT INTO products (prod_id, prod_name, prod_desc, price, unit) VALUES ('19', 'office', 'ms office software', 196, '23');
INSERT INTO products (prod_id, prod_name, prod_desc, price, unit) VALUES ('17', 'Apple', 'apple cell phone', 500, '10');
INSERT INTO products (prod_id, prod_name, prod_desc, price, unit) VALUES ('20', 'Apple', 'apple cell phone', 500, '10');
INSERT INTO products (prod_id, prod_name, prod_desc, price, unit) VALUES ('36', 'office', 'ms office software', 196, '23');
INSERT INTO products (prod_id, prod_name, prod_desc, price, unit) VALUES ('37', 'Apple', 'apple cell phone', 500, '10');
INSERT INTO products (prod_id, prod_name, prod_desc, price, unit) VALUES ('38', 'Dell', 'dell computer', 3000, '5');
INSERT INTO products (prod_id, prod_name, prod_desc, price, unit) VALUES ('39', 'office', 'ms office software', 196, '23');
INSERT INTO products (prod_id, prod_name, prod_desc, price, unit) VALUES ('21', 'Dell', 'dell computer', 3000, '5');
INSERT INTO products (prod_id, prod_name, prod_desc, price, unit) VALUES ('22', 'office', 'ms office software', 196, '23');
INSERT INTO products (prod_id, prod_name, prod_desc, price, unit) VALUES ('23', 'office', 'ms office software', 196, '23');
INSERT INTO products (prod_id, prod_name, prod_desc, price, unit) VALUES ('24', 'Apple', 'apple cell phone', 500, '10');
INSERT INTO products (prod_id, prod_name, prod_desc, price, unit) VALUES ('25', 'Dell', 'dell computer', 3000, '5');
INSERT INTO products (prod_id, prod_name, prod_desc, price, unit) VALUES ('26', 'office', 'ms office software', 196, '23');
INSERT INTO products (prod_id, prod_name, prod_desc, price, unit) VALUES ('27', 'Apple', 'apple cell phone', 500, '10');
INSERT INTO products (prod_id, prod_name, prod_desc, price, unit) VALUES ('28', 'Dell', 'dell computer', 3000, '5');
INSERT INTO products (prod_id, prod_name, prod_desc, price, unit) VALUES ('29', 'office', 'ms office software', 196, '23');
INSERT INTO products (prod_id, prod_name, prod_desc, price, unit) VALUES ('30', 'Apple', 'apple cell phone', 500, '10');
INSERT INTO products (prod_id, prod_name, prod_desc, price, unit) VALUES ('31', 'Dell', 'dell computer', 3000, '5');
INSERT INTO products (prod_id, prod_name, prod_desc, price, unit) VALUES ('32', 'office', 'ms office software', 196, '23');
INSERT INTO products (prod_id, prod_name, prod_desc, price, unit) VALUES ('33', 'office', 'ms office software', 196, '23');
INSERT INTO products (prod_id, prod_name, prod_desc, price, unit) VALUES ('34', 'Apple', 'apple cell phone', 500, '10');
INSERT INTO products (prod_id, prod_name, prod_desc, price, unit) VALUES ('35', 'Dell', 'dell computer', 3000, '5');
