logging.level:
  net.shyshkin: debug
app.external.product-service.url: http://localhost:8090

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: never
      schema-locations: jdbc/products-schema.sql
      data-locations: jdbc/products-data.sql

---
spring:
  config:
    activate:
      on-profile: mysql

  datasource:
    url: jdbc:mysql://localhost:23306/batch_db
    username: batch_user
    password: batch_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  batch:
    jdbc:
      platform: mysql
      initialize-schema: embedded
