logging.level:
  net.shyshkin: debug
app.processor.pause: 300
debug: true
app.tasklet.pause:
  download: 500
  file-process: 1000
  business3: 1000
  business4: 1000
  clean-up: 100
---
spring:
  config:
    activate:
      on-profile: mysql

  datasource:
    url: jdbc:mysql://localhost:23306/batch_db
    username: batch_user
    password: batch_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  batch:
    jdbc:
      platform: mysql
      initialize-schema: embedded